### ISSUE TITLE
Add Marketplace Transaction Fee

### ISSUE THREAD

**Issue by cryptnotiq** [FraktalNFT/dapp-UI#11]
A transaction fee from each transaction is sent to the DAO Bank as mentioned in https://gist.github.com/cryptnotiq/34feb66a9ec70aacb7c89163834e94d6 

The DAO also must have the ability to call a function to update the fee (via minion).

**Comment by earth2travis** [comment]
Need calls for contract and accounts

**Comment by cryptnotiq** [comment]
I believe this is done?

**Comment by cryptnotiq** [comment]
Let's put in the testnet DAO Bank address to test this @DrHongos 0x721c1016044a7bd95332601bcbcf889f958be5b2

**Comment by earth2travis** [comment]
1% Fee in place. Can be updated
