### ISSUE TITLE
Update Marketplace Listing UI

### ISSUE THREAD

**Issue by cryptnotiq** [FraktalNFT/dapp-UI#13]
## URL

https://fraktal-dapp.vercel.app/nft/0x0ebdf68ea31cecfd048f819b2a59a7bbe3894b82-0x6/fix-price-sale

## Current

See Screenshot

## Desired

Flip order so..
Fraktions on sale comes first 
Price per fraktion comes second

Replace Right side (Contributed) heading with title: 'Full NFT Value'
underneath the price which is calculated by [price per fraktion] * 10,000

**Screenshot**

![image](https://user-images.githubusercontent.com/43958441/129306567-26c05fab-fc05-46ac-bfe7-d4c09780d7ff.png)

**Comment by earth2travis** [comment]
Can we clarify what needs to be completed with this, "underneath the price which is calculated by [price per fraktion] * 10,000"?

**Comment by cryptnotiq** [comment]
On the right side, just display the full value of the NFT. Section title: Full NFT Value : 10,000 * price per fraktion.

This way someone can easily see the rate of the NFT they are investing in. i.e if 1,000 of fraktions are listed for 1 ETH, it would dispaly 10 ETH as the total value of the NFT.

**Comment by cryptnotiq** [comment]
You can also do the same exact thing for issue #12 and ignore everything else in that issue.
