### ISSUE TITLE
Add Unlist from Marketplace

### ISSUE THREAD

**Issue by cryptnotiq** [FraktalNFT/dapp-UI#17]
## URL

![image](https://user-images.githubusercontent.com/43958441/129307657-e059a322-432d-4412-9350-f22ea904bde9.png)

## Current

When Fraktions are already on marketplace, List takes user to screenshot 1 where they can unlist the asset.

## Desired

No need for separate screen. List was changed to Sell in issue #9 and if already on marketplace can change from 'Sell' to 'Unlist' which removes listing from marketplace. This also needs confirmation screens when signed in metamask.

No need to be able to edit listing for this first release.

## Screenshot

1
![image](https://user-images.githubusercontent.com/43958441/129307696-83e5b3ef-c1c8-4546-bfce-a05070d1d454.png)

2
![image](https://user-images.githubusercontent.com/43958441/129307714-24bf96dc-1b46-4a8a-aea5-2f438682c017.png)

**Comment by earth2travis** [comment]
Remove Update Data and Unlist view until later
Once listed button List button says Unlist

**Comment by cryptnotiq** [comment]
I think @DrHongos demoed this in the last call but I can't find in the UI where it was updated.

**Comment by DrHongos** [comment]
This was implemented in previous demos, but working improperly, 
pushed correction to high id's (converted to hex) on PR #9
![image](https://user-images.githubusercontent.com/18542003/134256064-05dacb9e-fe6a-423d-a9e0-4c5879d22710.png)
