### ISSUE TITLE
Unlock Fraktions When Minting NFT

### ISSUE THREAD

**Issue by cryptnotiq** [FraktalNFT/dapp-UI#5]
**URL**
https://fraktal-dapp.vercel.app/mint-nft

**Current**

When you mint an NFT, it also mints 10,000 (not sure what the exact number is) Fraktions and releases both to the users wallet.

**Desired**
Both the full NFT and the Fraktions cannot both be unlocked at the same time. When the user mints the NFT, the full NFT goes to the users wallet and Fraktions should be locked in the contract. The user can choose to lock the full NFT to unlock the fraktions and vice versa.

**Comment by earth2travis** [comment]
So do we want to automatically fractionalize NFTs when minting?
