### ISSUE TITLE
Update MY NFTs UI/UX

### ISSUE THREAD

**Issue by cryptnotiq** [FraktalNFT/dapp-UI#8]
## URL

https://fraktal-dapp.vercel.app/my-nfts

## Current

Options for full NFTs are:

1. List
2. Manage

## Desired

Only 1 button, 2 states.

**State 1**: NFT Unlocked = Button says 'Fractionalise' -> Brings to Fractionalise Page which can be a simplified version of screenshot 2 below. Change message to 'Lock the NFT to receive Fraktions'. Everything else can be removed except The Lock / Transfer Buttons. User selects lock, confirms in metamask, and once confirmed, Transfer (rename to 'withdraw') becomes active and click and confirm that in metamask to withdraw fraktions. 

**State 2**: NFT Locked = Button says 'Unlock' -> See screenshot 3. Just have the unlock NFT by locking 100% of Fraktions.

## Screenshots

1
![image](https://user-images.githubusercontent.com/43958441/129303789-22d486de-b77c-497d-9ff5-64b31f32cba5.png)

2 
![image](https://user-images.githubusercontent.com/43958441/129303990-9505cd4a-1574-4261-b3bf-b06290efaec3.png)

3

### Current

![image](https://user-images.githubusercontent.com/43958441/129304234-61d4531f-b93f-4fc5-aed2-30550d323140.png)

### Desired 

![image](https://user-images.githubusercontent.com/43958441/129304279-f54138bc-5cbc-4ec4-a01a-a1050e88555b.png)

**Comment by cryptnotiq** [comment]
I think we can keep this really simple for now actually and just direct the users to the same listing page, and if they only want fraktions but not to sell they just don't proceed with listing after the NFT is locked and fractionalised.

**Comment by cryptnotiq** [comment]
also please see issue #4 to add the buyout function and vote to the unlock page UI here

**Comment by earth2travis** [comment]
### My NFTs

Cards should have buttons that say:

- Import
- Fraktionalize

You should not be able to manage an NFT that is not fractionalized.

### My Fraktions

Cards should have buttons that say:

- Sell (takes you to list item page)
- Manage

Once fraktionalized the cards should disappear from My NFTs and be listed under My Fraktions

**Comment by earth2travis** [comment]
Rewrite component for two types of cards. (My NFTs and My Fraktions)

Allow import of both 1155 and 721
