### ISSUE TITLE
Update My Fraktions UI/UX

### ISSUE THREAD

**Issue by cryptnotiq** [FraktalNFT/dapp-UI#9]
## URL

https://fraktal-dapp.vercel.app/my-nfts

## Current

See screenshot

## Desired

- Change List button text to 'Sell'
- 'Claim' should batch claim revenue from all different fractional NFT shares (fraktions)

## Screenshots

![image](https://user-images.githubusercontent.com/43958441/129304870-d7be254f-2314-42d4-a67d-4fdcae3dcccc.png)

**Comment by earth2travis** [comment]
Should this be broken into two issues?

- Change List button text to 'Sell'
- Batch claim revenue

**Comment by earth2travis** [comment]
- Will users know what "Claim from manage" means?
- Is there a better label than "Claim from manage"

**Comment by cryptnotiq** [comment]
> * Will users know what "Claim from manage" means?
> * Is there a better label than "Claim from manage"

I would just say Claim or Claim Revenue
